### ISSUE TITLE
Sound output is very quiet

### ISSUE THREAD

**Issue by TechGuard** [lukasjapan/bt-speaker#1]
This is the best solution that I could find that works with the PI 3.
But the sound output is currently very low. Is there a way to boost the output volume?

I already have the volume at 100% and I noticed it is a common problem with ALSA.

**Comment by lukasjapan** [comment]
Sorry for late reply, I was on vacation.

I just checked this on my Pi3 (2017-01-11-raspbian-jessie-lite.img installed with no modifications in the ALSA system). I used the retail iPhone headphones that ship with the iPhone 6.

The sound output was reasonably loud, so the only thing I can suggest is to double check the volume settings in `alsamixer`. The bar should change automatically according to the client device settings and hit 100% on maximum volume.

If alsamixer is showing 100% and the volume is still too low it must be an issue of the headphone/speaker or the ALSA configuration itself and is not a problem of bt-speaker and can't be fixed in this repository.

I am going to close this issue as unconfirmed/unrelated.

P.S.
The code that changes the volume can be found [here](https://github.com/lukasjapan/bt-speaker/blob/master/bt_speaker.py#L51)
